insert into rental_point (id, point_name) values (1, 'Maciejowice');
insert into rental_point (id, point_name) values (2, 'Andoany');
insert into rental_point (id, point_name) values (3, 'Burgos');
insert into rental_point (id, point_name) values (4, 'Shiroi');
insert into rental_point (id, point_name) values (5, 'Regente Feijó');
insert into rental_point (id, point_name) values (6, 'Terang');
insert into rental_point (id, point_name) values (7, 'Jiangyan');
insert into rental_point (id, point_name) values (8, 'A’ershan');
insert into rental_point (id, point_name) values (9, 'Slavyanovo');
insert into rental_point (id, point_name) values (10, 'Buluh Kasap');
insert into rental_point (id, point_name) values (11, 'Katoúna');
insert into rental_point (id, point_name) values (12, 'Zhanqian');
insert into rental_point (id, point_name) values (13, 'Galižana');
insert into rental_point (id, point_name) values (14, 'Stockholm');
insert into rental_point (id, point_name) values (15, 'Hostomice');
insert into rental_point (id, point_name) values (16, 'Barra Bonita');
insert into rental_point (id, point_name) values (17, 'Laâyoune / El Aaiún');
insert into rental_point (id, point_name) values (18, 'Dawu Chengguanzhen');
insert into rental_point (id, point_name) values (19, 'Dowlatyār');
insert into rental_point (id, point_name) values (20, 'Stockholm');
insert into rental_point (id, point_name) values (21, 'Ayrihuanca');
insert into rental_point (id, point_name) values (22, 'Huaidian');
insert into rental_point (id, point_name) values (23, 'Besukrejo');
insert into rental_point (id, point_name) values (24, 'Imotski');
insert into rental_point (id, point_name) values (25, 'Camden');
insert into rental_point (id, point_name) values (26, 'Wangyi Zhendian');
insert into rental_point (id, point_name) values (27, 'Xixiang');
insert into rental_point (id, point_name) values (28, 'Brive-la-Gaillarde');
insert into rental_point (id, point_name) values (29, 'Progreso');
insert into rental_point (id, point_name) values (30, 'Huanghai');
