create table cars (
	id INT,
	vendor_model_name DECIMAL(10,2),
	govern_number VARCHAR(50)
);
insert into cars (id, vendor_model_name, govern_number) values (1, 'Hyundai Accent', 'B5900YM');
insert into cars (id, vendor_model_name, govern_number) values (2, 'GMC 3500', 'Q3392MW');
insert into cars (id, vendor_model_name, govern_number) values (3, 'GMC 3500', 'V7332SK');
insert into cars (id, vendor_model_name, govern_number) values (4, 'Buick Rendezvous', 'D7126KF');
insert into cars (id, vendor_model_name, govern_number) values (5, 'Ford Galaxie', 'O1790AD');
insert into cars (id, vendor_model_name, govern_number) values (6, 'Hyundai Accent', 'X4943DL');
insert into cars (id, vendor_model_name, govern_number) values (7, 'Jaguar XK Series', 'X8451SH');
insert into cars (id, vendor_model_name, govern_number) values (8, 'Mercedes-Benz C-Class', 'E4910MR');
insert into cars (id, vendor_model_name, govern_number) values (9, 'Pontiac Grand Am', 'X2174BQ');
insert into cars (id, vendor_model_name, govern_number) values (10, 'Ford Contour', 'S7340GR');
insert into cars (id, vendor_model_name, govern_number) values (11, 'GMC Vandura 1500', 'V5430OL');
insert into cars (id, vendor_model_name, govern_number) values (12, 'Mitsubishi Excel', 'N4536WK');
insert into cars (id, vendor_model_name, govern_number) values (13, 'Volkswagen Jetta', 'R7256LS');
insert into cars (id, vendor_model_name, govern_number) values (14, 'Lexus LX', 'N8070UU');
insert into cars (id, vendor_model_name, govern_number) values (15, 'Toyota RAV4', 'J3648GI');
insert into cars (id, vendor_model_name, govern_number) values (16, 'Ford LTD', 'V1814GY');
insert into cars (id, vendor_model_name, govern_number) values (17, 'Chevrolet Beretta', 'L0987CK');
insert into cars (id, vendor_model_name, govern_number) values (18, 'Dodge Charger', 'X7486SL');
insert into cars (id, vendor_model_name, govern_number) values (19, 'Isuzu i-Series', 'W5783AM');
insert into cars (id, vendor_model_name, govern_number) values (20, 'Mercedes-Benz S-Class', 'J9930PS');
insert into cars (id, vendor_model_name, govern_number) values (21, 'Buick Somerset', 'O2590MO');
insert into cars (id, vendor_model_name, govern_number) values (22, 'Saab 9-3', 'R3526HS');
insert into cars (id, vendor_model_name, govern_number) values (23, 'Honda Civic', 'F0008ZW');
insert into cars (id, vendor_model_name, govern_number) values (24, 'Porsche 911', 'Z8921VA');
insert into cars (id, vendor_model_name, govern_number) values (25, 'Nissan Quest', 'Z5931SJ');
insert into cars (id, vendor_model_name, govern_number) values (26, 'Buick Regal', 'F4196FS');
insert into cars (id, vendor_model_name, govern_number) values (27, 'Lexus HS', 'F4069WB');
insert into cars (id, vendor_model_name, govern_number) values (28, 'Mazda MX-5', 'D2296MG');
insert into cars (id, vendor_model_name, govern_number) values (29, 'Pontiac Firebird', 'P2172BP');
insert into cars (id, vendor_model_name, govern_number) values (30, 'Chevrolet Express 2500', 'O4969YZ');
insert into cars (id, vendor_model_name, govern_number) values (31, 'Audi A6', 'V8172ZS');
insert into cars (id, vendor_model_name, govern_number) values (32, 'Chevrolet Corvette', 'M7787ED');
insert into cars (id, vendor_model_name, govern_number) values (33, 'Volkswagen Passat', 'Y0962TF');
insert into cars (id, vendor_model_name, govern_number) values (34, 'BMW 1 Series', 'R0052NY');
insert into cars (id, vendor_model_name, govern_number) values (35, 'Lincoln Town Car', 'G3272YS');
insert into cars (id, vendor_model_name, govern_number) values (36, 'Saab 9-5', 'F3987HW');
insert into cars (id, vendor_model_name, govern_number) values (37, 'Mercedes-Benz SLK-Class', 'Z3894VF');
insert into cars (id, vendor_model_name, govern_number) values (38, 'Pontiac G8', 'K5503AI');
insert into cars (id, vendor_model_name, govern_number) values (39, 'Mercury Mountaineer', 'W1169CR');
insert into cars (id, vendor_model_name, govern_number) values (40, 'Hyundai Sonata', 'Q9299MM');
insert into cars (id, vendor_model_name, govern_number) values (41, 'Infiniti QX56', 'V0421TW');
insert into cars (id, vendor_model_name, govern_number) values (42, 'Ford Explorer Sport Trac', 'S6484XU');
insert into cars (id, vendor_model_name, govern_number) values (43, 'Mazda CX-9', 'W2722LD');
insert into cars (id, vendor_model_name, govern_number) values (44, 'Ford Mustang', 'P1387GK');
insert into cars (id, vendor_model_name, govern_number) values (45, 'Ford E150', 'Z8949RE');
insert into cars (id, vendor_model_name, govern_number) values (46, 'Mazda Familia', 'O6305OF');
insert into cars (id, vendor_model_name, govern_number) values (47, 'Kia Sportage', 'Q1211TX');
insert into cars (id, vendor_model_name, govern_number) values (48, 'Dodge Intrepid', 'U3776BY');
insert into cars (id, vendor_model_name, govern_number) values (49, 'Chrysler Fifth Ave', 'Y3632DI');
insert into cars (id, vendor_model_name, govern_number) values (50, 'Chevrolet Lumina', 'E8694JH');
insert into cars (id, vendor_model_name, govern_number) values (51, 'Audi Coupe GT', 'I3979FK');
insert into cars (id, vendor_model_name, govern_number) values (52, 'Honda Civic Si', 'A3186HD');
insert into cars (id, vendor_model_name, govern_number) values (53, 'Mitsubishi Eclipse', 'F1139LQ');
insert into cars (id, vendor_model_name, govern_number) values (54, 'GMC Sierra 2500', 'G2544GQ');
insert into cars (id, vendor_model_name, govern_number) values (55, 'Toyota Corolla', 'G2786OC');
insert into cars (id, vendor_model_name, govern_number) values (56, 'Cadillac SRX', 'L3068MA');
insert into cars (id, vendor_model_name, govern_number) values (57, 'Mercedes-Benz SL-Class', 'N3435HF');
insert into cars (id, vendor_model_name, govern_number) values (58, 'Land Rover LR2', 'H3178OQ');
insert into cars (id, vendor_model_name, govern_number) values (59, 'Suzuki Grand Vitara', 'A8676HZ');
insert into cars (id, vendor_model_name, govern_number) values (60, 'Jeep Cherokee', 'X7484SP');
insert into cars (id, vendor_model_name, govern_number) values (61, 'Ford Laser', 'C0199TW');
insert into cars (id, vendor_model_name, govern_number) values (62, 'Ford F350', 'W9307PY');
insert into cars (id, vendor_model_name, govern_number) values (63, 'Mitsubishi Galant', 'N1329DT');
insert into cars (id, vendor_model_name, govern_number) values (64, 'Volvo XC70', 'H4442DG');
insert into cars (id, vendor_model_name, govern_number) values (65, 'Oldsmobile Silhouette', 'C5443ZD');
insert into cars (id, vendor_model_name, govern_number) values (66, 'Audi A5', 'F7211RA');
insert into cars (id, vendor_model_name, govern_number) values (67, 'Smart Fortwo', 'R6061GZ');
insert into cars (id, vendor_model_name, govern_number) values (68, 'Dodge Grand Caravan', 'L9852QD');
insert into cars (id, vendor_model_name, govern_number) values (69, 'Buick Century', 'U2767ZM');
insert into cars (id, vendor_model_name, govern_number) values (70, 'Ford ZX2', 'V3612AU');
insert into cars (id, vendor_model_name, govern_number) values (71, 'Mitsubishi Pajero', 'B4646BD');
insert into cars (id, vendor_model_name, govern_number) values (72, 'Chevrolet Corvair', 'Q2468QI');
insert into cars (id, vendor_model_name, govern_number) values (73, 'Dodge Nitro', 'S9687BK');
insert into cars (id, vendor_model_name, govern_number) values (74, 'GMC Yukon XL 1500', 'O3635PY');
insert into cars (id, vendor_model_name, govern_number) values (75, 'Plymouth Colt', 'A9536WR');
insert into cars (id, vendor_model_name, govern_number) values (76, 'Lexus LX', 'U0476ZM');
insert into cars (id, vendor_model_name, govern_number) values (77, 'Buick Century', 'Z2576TP');
insert into cars (id, vendor_model_name, govern_number) values (78, 'Buick Rendezvous', 'Q4751CL');
insert into cars (id, vendor_model_name, govern_number) values (79, 'Ford Focus', 'M2581VJ');
insert into cars (id, vendor_model_name, govern_number) values (80, 'Dodge Ram', 'T8312FZ');
insert into cars (id, vendor_model_name, govern_number) values (81, 'Pontiac Grand Prix', 'V1992OW');
insert into cars (id, vendor_model_name, govern_number) values (82, 'Mercedes-Benz SL-Class', 'Y7181NB');
insert into cars (id, vendor_model_name, govern_number) values (83, 'Nissan Altima', 'F3335BL');
insert into cars (id, vendor_model_name, govern_number) values (84, 'Ford E350', 'I7372GE');
insert into cars (id, vendor_model_name, govern_number) values (85, 'Buick Coachbuilder', 'G3362WK');
insert into cars (id, vendor_model_name, govern_number) values (86, 'Chevrolet Corvette', 'G4347LD');
insert into cars (id, vendor_model_name, govern_number) values (87, 'Lexus GX', 'D7266KF');
insert into cars (id, vendor_model_name, govern_number) values (88, 'Mercedes-Benz E-Class', 'M2217FG');
insert into cars (id, vendor_model_name, govern_number) values (89, 'Saab 9-3', 'K7727EW');
insert into cars (id, vendor_model_name, govern_number) values (90, 'Lexus RX', 'E4966LA');
insert into cars (id, vendor_model_name, govern_number) values (91, 'Ford E350', 'S9390DY');
insert into cars (id, vendor_model_name, govern_number) values (92, 'Chevrolet Cruze', 'S6899FC');
insert into cars (id, vendor_model_name, govern_number) values (93, 'Ford Econoline E150', 'T9026MM');
insert into cars (id, vendor_model_name, govern_number) values (94, 'Volkswagen Vanagon', 'V6106SF');
insert into cars (id, vendor_model_name, govern_number) values (95, 'Chevrolet Caprice', 'B5151WP');
insert into cars (id, vendor_model_name, govern_number) values (96, 'Maybach 57', 'C8833HS');
insert into cars (id, vendor_model_name, govern_number) values (97, 'Chevrolet Corsica', 'S0145HL');
insert into cars (id, vendor_model_name, govern_number) values (98, 'Lexus RX', 'W1439FT');
insert into cars (id, vendor_model_name, govern_number) values (99, 'Chevrolet Suburban', 'P5338TW');
insert into cars (id, vendor_model_name, govern_number) values (100, 'Mercedes-Benz C-Class', 'M6562GT');
